[settings]
paranoid = true

[tools]
"core:bun" = "latest"
"core:deno" = "latest"
"core:go" = "latest"
"core:node" = "lts"
"core:rust" = "latest"
"github:astral-sh/uv" = "latest"
"github:cli/cli" = "latest"
"github:hadolint/hadolint" = "latest"
"github:jj-vcs/jj" = "latest"
"github:jqlang/jq" = "latest"
"github:junegunn/fzf" = "latest"
"github:koalaman/shellcheck" = "latest"
"github:mvdan/sh" = { version = "latest", bin = "shfmt" }
"github:ollama/ollama" = "latest"
"github:rails/rails-new" = "0.5.0"
"github:rclone/rclone" = "latest"
"gitlab:gitlab-org/cli" = "latest"
"go:code.gitea.io/tea" = "main"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@biomejs/biome" = "latest"
"npm:@bitwarden/cli" = "latest"
"npm:@github/copilot" = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:@openai/codex" = "latest"
"npm:@originator-profile/opvc" = "latest"
"npm:appwrite-cli" = "latest"
"npm:heroku" = "latest"
"npm:lighthouse" = "latest"
"npm:playwright" = "latest"
"npm:pnpm" = "latest"
"npm:serve" = "latest"
"npm:tailwindcss" = "latest"
"npm:wrangler" = "latest"
"npm:zx" = "latest"
